// <auto-generated />
using System;
using API_Sucursales_Practica.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Sucursales_Practica.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241124181740_ThirdMigration")]
    partial class ThirdMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Sucursales_Practica.Domain.ConfiguracionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Configuraciones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4abfabb-c1c1-4bad-ab6a-5b57280398b4"),
                            Nombre = "padding-top",
                            Valor = "50px"
                        },
                        new
                        {
                            Id = new Guid("418cd697-aecc-440c-93c4-f2d0f8c9e4fb"),
                            Nombre = "padding-left",
                            Valor = "100px"
                        });
                });

            modelBuilder.Entity("Practica_API_Sucursales.Domain.ProvinciaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provincias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72a6acca-d30b-44b1-b56d-7c07c7806a3e"),
                            Nombre = "Buenos Aires"
                        },
                        new
                        {
                            Id = new Guid("3c303cf7-5158-469f-bd54-674cbf7a4919"),
                            Nombre = "Cordoba"
                        },
                        new
                        {
                            Id = new Guid("4ba03300-6238-4324-9e71-d28e909cfe3a"),
                            Nombre = "Santa Fe"
                        });
                });

            modelBuilder.Entity("Practica_API_Sucursales.Domain.SucursalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApellidoTitual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdProvincia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTipo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreTitular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProvincia");

                    b.HasIndex("IdTipo");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Practica_API_Sucursales.Domain.TipoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b832d7b-44c9-4158-95b4-1e01b0a1b285"),
                            Nombre = "Pequeña"
                        },
                        new
                        {
                            Id = new Guid("5508f652-5d4e-4e35-9b64-4a3fd033d4d1"),
                            Nombre = "Grande"
                        });
                });

            modelBuilder.Entity("Practica_API_Sucursales.Domain.SucursalEntity", b =>
                {
                    b.HasOne("Practica_API_Sucursales.Domain.ProvinciaEntity", "Provincia")
                        .WithMany()
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practica_API_Sucursales.Domain.TipoEntity", "Tipo")
                        .WithMany("SucursalEntities")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Practica_API_Sucursales.Domain.TipoEntity", b =>
                {
                    b.Navigation("SucursalEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
