// <auto-generated />
using System;
using API_Sucursales_Practica.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Sucursales_Practica.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241124180857_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Sucursales_Practica.Domain.ConfiguracionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Configuraciones");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ffea04c-7a46-4551-8ed3-0df6cd6fac2f"),
                            Nombre = "padding-top",
                            Valor = "50px"
                        },
                        new
                        {
                            Id = new Guid("54428a1a-8523-4a3c-95e8-5623066a3515"),
                            Nombre = "padding-left",
                            Valor = "100px"
                        });
                });

            modelBuilder.Entity("Practica_API_Sucursales.Domain.ProvinciaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provincias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f2d4f9b-bb35-48ce-b02d-9d3587bafff0"),
                            Nombre = "Buenos Aires"
                        },
                        new
                        {
                            Id = new Guid("3f7af306-b9c2-4c50-b291-ab4fab33161a"),
                            Nombre = "Cordoba"
                        },
                        new
                        {
                            Id = new Guid("8249917f-7c96-43cb-8c72-f7460ed65ff6"),
                            Nombre = "Santa Fe"
                        });
                });

            modelBuilder.Entity("Practica_API_Sucursales.Domain.SucursalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApellidoTitual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdProvincia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTipo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreTitular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProvincia");

                    b.HasIndex("IdTipo");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Practica_API_Sucursales.Domain.TipoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("91c544ee-eadf-4694-9fff-a05e31d3e028"),
                            Nombre = "Pequeña"
                        },
                        new
                        {
                            Id = new Guid("65e3efe6-bc45-4038-ae5a-787900a56ca5"),
                            Nombre = "Grande"
                        });
                });

            modelBuilder.Entity("Practica_API_Sucursales.Domain.SucursalEntity", b =>
                {
                    b.HasOne("Practica_API_Sucursales.Domain.ProvinciaEntity", "Provincia")
                        .WithMany()
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practica_API_Sucursales.Domain.TipoEntity", "Tipo")
                        .WithMany("SucursalEntities")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Practica_API_Sucursales.Domain.TipoEntity", b =>
                {
                    b.Navigation("SucursalEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
